// nco_lut.v
// Quarter-wave NCO lookup table with quadrant decode.
//
// ROM entry i stores {sin[QSIZE-1-i], sin[i]} (packed, unsigned magnitudes).
// One ROM read gives both sin and cos amplitudes for any phase via quadrant logic:
//
//   quadrant[1] → sin/cos sign
//   quadrant[0] → selects which packed half is sin vs cos amplitude
//
// sin/cos outputs are combinational (0-cycle latency) — register them upstream.
//
// ROM init: $readmemh from INIT_FILE (generated by pattern/gen_nco_rom.py).

module nco_lut #(
    parameter PHASE_W   = 16,
    parameter AMP_W     = 12,
    parameter INIT_FILE = "pattern/nco_rom.hex"
)(
    input  wire [PHASE_W-1:0]        phase,
    output wire signed [AMP_W-1:0]   sin_out,
    output wire signed [AMP_W-1:0]   cos_out
);
    localparam QASIZE = PHASE_W - 2;        // 14-bit quarter-table address
    localparam QSIZE  = 1 << QASIZE;       // 16384 entries

    wire [1:0]         quadrant = phase[PHASE_W-1 : PHASE_W-2];
    wire [QASIZE-1:0]  raw_idx  = phase[PHASE_W-3 : 0];

    // ROM: DEPTH=QSIZE, WIDTH=2*AMP_W (packed pair)
    wire [2*AMP_W-1:0] rom_word;

    rom #(
        .DSIZE     (2 * AMP_W),
        .ASIZE     (QASIZE),
        .INIT_FILE (INIT_FILE)
    ) u_rom (
        .rdata (rom_word),
        .raddr (raw_idx)
    );

    // rom_word[AMP_W-1:0]       = sin[raw_idx]        (lo half)
    // rom_word[2*AMP_W-1:AMP_W] = sin[QSIZE-1-raw_idx] (hi half)
    wire [AMP_W-1:0] lo = rom_word[AMP_W-1:0];
    wire [AMP_W-1:0] hi = rom_word[2*AMP_W-1:AMP_W];

    // quadrant[0]=0: sin uses lo (direct), cos uses hi (mirrored)
    // quadrant[0]=1: sin uses hi (mirrored), cos uses lo (direct)
    wire [AMP_W-1:0] sin_amp = quadrant[0] ? hi : lo;
    wire [AMP_W-1:0] cos_amp = quadrant[0] ? lo : hi;

    wire sin_sign = quadrant[1];
    wire cos_sign = quadrant[1] ^ quadrant[0];

    // Magnitudes are unsigned [0, 2^(AMP_W-1)-1], so MSB is always 0.
    // Negation fits in AMP_W signed (worst case: -2047 in 12-bit signed).
    assign sin_out = sin_sign ? -$signed(sin_amp) : $signed(sin_amp);
    assign cos_out = cos_sign ? -$signed(cos_amp) : $signed(cos_amp);

endmodule
